### ISSUE TITLE
sidebar functionality is not working

### ISSUE THREAD

**Issue by HimanshuNarware** [HimanshuNarware/Devlabs#2] opened 2023-09-26 05:24 UTC
Description
sidebar functionality is not working
screenshot
![sidebar](https://github.com/HimanshuNarware/Devlabs/assets/83147410/56bf6a6a-a029-47de-b8d8-07acb053ab83)

**Comment by ani-netizen** [comment] 2023-09-26 05:52
what technologies are used

**Comment by ani-netizen** [comment] 2023-09-26 06:54
Hello Himanshu 

From your code and screenshot what I get is you want to toggle div with id sidebar(attached screenshot of code). Please let me know if I am correct or not

![image](https://github.com/HimanshuNarware/Devlabs/assets/83304810/4b49583e-6883-4056-9c1a-e6de0319f399)

**Comment by Vidhanvyrs** [comment] 2023-09-26 07:27
Hey let me know if the issue is fixed or not 'cause i could help in it as i faced a similar problem in my previous contribution

**Comment by HimanshuNarware** [comment] 2023-09-26 08:01
> Hello Himanshu
> 
> From your code and screenshot what I get is you want to toggle div with id sidebar(attached screenshot of code). Please let me know if I am correct or not. If yes you can assign this to me
> 
> ![image](https://user-images.githubusercontent.com/83304810/270562859-4b49583e-6883-4056-9c1a-e6de0319f399.png)

 @ani-netizen Yep

**Comment by ani-netizen** [comment] 2023-09-26 10:07
> > Hello Himanshu
> > From your code and screenshot what I get is you want to toggle div with id sidebar(attached screenshot of code). Please let me know if I am correct or not. If yes you can assign this to me
> > ![image](https://user-images.githubusercontent.com/83304810/270562859-4b49583e-6883-4056-9c1a-e6de0319f399.png)
> 
> @ani-netizen Yep

assign this to me I can help you with this issue along with some other improvements that I see

**Comment by Vayras** [comment] 2023-09-26 12:37
@HimanshuNarware solved the issue

**Closed** 2024-05-10 19:11 UTC
Labels: good first issue, hacktoberfest
